### ISSUE TITLE
Is puppet-teleport GitHub Repo Active?

### ISSUE THREAD

**Issue by bitvijays** [jaxxstorm/puppet-teleport#29]
Dear @jaxxstorm 

Hope you are doing well. Just wanted to know. Is this repo still active and happy to accept Pull Requests?

Kind Regards,
bitvijays

**Comment by jaxxstorm** [comment]
Hi @bitvijays - no. I'm no longer a puppet user so don't maintain this module. I'll archive it so that it's clearer
